[sources.openaq]
api_key = "9b02bfa6ccca978849df44495ccfff76846d2b52f508cc5c0612876e487cf49d"


[destination.snowflake.credentials]

username = "SHAHMEER7008"
password = "Shahmeerzaidi1214"

host = "ch79706.me-central2.gcp"

database = "GITHUB_DB"

warehouse = "GITHUB_WH"

role = "ACCOUNTADMIN"