FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DAGSTER_HOME=/app

EXPOSE 3000

CMD ["dagster","dev","-h","0.0.0.0","-p","3000"]